language: node_js
node_js: stable
branches:
  only:
  - source
env:
  global:
    secure: IxFGxSDIe6P80fyyTYYC5GIIJek1t4AqkIuRaMl9nmW4qFHYIAqsiqKO2S3584BtBDSbN2GoGIsNQjE02hjHjUGxddndk5i+eCY3JkxeMY4RKxiAv2BivAwfzj3SycrBAuDi5Pafi6yHLV4GV7sqqlzwFzw1c1Sc1DG0Gs1/X6VUrH9Nvbwha6KAvaQSNeS+6XugsJEZzNm9uygb98uJHDBKkRlNL9Tb3eSW76v1NMg+Anwv+UJiQOHOru/1xN5FwilZDlsdtnWjPwzjM+ccL7muT8nVJmIGxws0ov881HDGObMa5tcbyy9QIeSw+wdH+OkjwD6H+WrNsXP+22BaQGfoXqsVxgjE6mnFziESjHROMRJ/ZLDlL9TIE7/fq5F2dh1vwp9Oo7UKQEJQ4z9UUbEDC8OtVwFOHf6C8pLnvp3iEowUWllHUYCHf7pkWVIDT/4HkevtrCjHpWXgeCPXcV636qRyhEb6g1nnn0T9sYmdYXeoY9GUQ4ffYyETwXbI5/GZHD0FTroVbDbmk1tbUxckHOyc3Vqml0MP7gyFv8OpUJvY6VA+Y+jsOUib02zlcMsh+boJumu73qmzgf0gpVmde1kpNN6qDknCuwM92CZzhQVz3oAzCmYZ3EUZiWjvpu89OhT70NIezfAfhxckxqvW2g91GvQ/71B8X+Pycy4=
before_install:
- git config --global user.name "Dreamacro"
- git config --global user.email chuainian@gmail.com
- npm install hexo -g
script:
- hexo g
- sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
- hexo d
