language: node_js
node_js: stable
cache:
  directories:
  - node_modules
  - $(npm root -g)
  - $(npm config get prefix)/bin/hexo
branches:
  only:
  - source
env:
  global:
    secure: fsC8ZnilVGI6JoAch2ZPWM12MGWJscH9su66BCT3fx6HRhEQVnuFToQePcjSBr+D3FUUpCAt78jAZdqTTFDMaEroRrOAnUkwF4dcAuPApQ6gBg6R4oiS+u6g2X9PfOztTSvOGzQOi3egmRGGh0XVPQBhKofFrZDZgwBmzXE9btCH8cZPk2FprhbG/2jHOOnIHZawMwBkfAzvVwlassJBDjarLvtLa2AXCgVlVl9YY6DoaZikzBd5AsM2NHb4kx6QReaRt53GHUSROfVg9C18qIxxyPUPSUqlJ0HRPwV9yWHEotljDmYeCe7Ry0suW2/dkIzNHuS1akS9wXdqiO0LpaP5XFtITh8Ipdtnpz6lwvWCy3huTQYZ8ZoR48g+n5kwg6ZxTFK/3aCzCOZoeAMD4XD8CMW8yntraRnFsgJecm818FXmSX8ek6ErQKBbeRO25z+f47ttBMF+H/7fB6bI+2bzHtyPRw8cZtDStQuB6GkmU9R6RDii+vRjnFalzLFR1OJ40hZLRe75OPqQck1z+ZgW0esWdYvlvABmd7ZPqTCXfyGDTwnN9HN65UBeB18pOjIr+6rQYs1eIT68UxmOpCI+MFpRkHeDCi9Zml2+IbLL75pfRE49eOX8BUiBQz/LvCJ5uLkXg/nLZH8zTPSJhPauOvKoiOnY25acbtFZ8LU=
before_install:
- git config --global user.name "Dreamacro"
- git config --global user.email chuainian@gmail.com
- npm install hexo -g
script:
- hexo g
- sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
- hexo d
